In [1]:
import pandas as pd

df = pd.read_excel("../data/raw/OLA_DataSet.xlsx")
df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...

In [3]:
df.shape

(103024, 20)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[ns]
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  object
 3   Booking_Status              103024 non-null  object
 4   Customer_ID                 103024 non-null  object
 5   Vehicle_Type                103024 non-null  object
 6   Pickup_Location             103024 non-null  object
 7   Drop_Location               103024 non-null  object
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  10499 non-null   object
 11  Canceled_Rides_by_Driver    18434 non-null   object
 12  Incomplete_Rides            63967 non-null   object
 13  Incomplete_Rides_Reason     3926 non-null    object
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              63967 non-null   object
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              103024 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(2), object(13)
memory usage: 15.7+ MB

In [7]:
df.describe(include="all")

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
count,103024,103024,103024,103024,103024,103024,103024,103024,63967.000000,63967.000000,10499,18434,63967,3926,103024.000000,63967,103024.000000,63967.000000,63967.000000,103024
unique,NaN,1440,103024,4,94544,7,50,50,NaN,NaN,5,4,2,3,NaN,4,NaN,NaN,NaN,7
top,NaN,00:53:00,CNR3204013257,Success,CID954071,Prime Sedan,Banashankari,Peenya,NaN,NaN,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,NaN,Cash,NaN,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
freq,NaN,101,1,63967,5,14877,2201,2159,NaN,NaN,3175,6542,60041,1601,NaN,35022,NaN,NaN,NaN,14877
mean,2024-07-16 11:31:38.879678720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170.876952,84.873372,NaN,NaN,NaN,NaN,548.751883,NaN,14.189927,3.997457,3.998313,NaN
min,2024-07-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.000000,25.000000,NaN,NaN,NaN,NaN,100.000000,NaN,0.000000,3.000000,3.000000,NaN
25%,2024-07-08 18:41:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.000000,55.000000,NaN,NaN,NaN,NaN,242.000000,NaN,0.000000,3.500000,3.500000,NaN
50%,2024-07-16 11:23:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168.000000,85.000000,NaN,NaN,NaN,NaN,386.000000,NaN,8.000000,4.000000,4.000000,NaN
75%,2024-07-24 05:18:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,238.000000,115.000000,NaN,NaN,NaN,NaN,621.000000,NaN,26.000000,4.500000,4.500000,NaN
max,2024-07-31 23:58:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,308.000000,145.000000,NaN,NaN,NaN,NaN,2999.000000,NaN,49.000000,5.000000,5.000000,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.803640,36.005100,NaN,NaN,NaN,NaN,536.541221,NaN,15.776270,0.576834,0.578957,NaN

### Key Columns Identified

- booking_status: Indicates whether the ride was completed, cancelled, or incomplete
- vehicle_type: Type of vehicle used for the ride
- payment_method: Mode of payment used by customer
- booking_value: Total fare amount for the ride
- ride_distance: Distance covered during the ride
- customer_rating: Rating given by customer
- driver_rating: Rating given to driver
- cancellation_reason: Reason for cancellation (customer or driver)

### Initial Questions from the Data

1. Which time periods have the highest ride demand?
2. Which vehicle types generate the most distance and revenue?
3. What are the major reasons for ride cancellations?
4. How do customer and driver ratings compare?
5. Which payment methods contribute most to revenue?